### ISSUE TITLE
Do you have plans to switch to System.Text.Json?

### ISSUE THREAD

**Issue by vadimkhm** [rajanadar/VaultSharp#304] opened 2023-02-18 06:58 UTC
In our projects, we are using only System.Text.Json, and it is disallowed to have a different parser, it would be great to see that VaultSharp switched to  System.Text.Json

Thanks

**Comment by rajanadar** [comment] 2023-02-18 18:13
hi @vadimkhm , let me assess the impact of that change and get back to you

**Comment by rajanadar** [comment] 2023-02-18 18:38
i did an assessment @vadimkhm , it is a 2300 place change with regression testing. It also needs me to stop supporting anything before .NET 4.7.2 and .NET 1.3

That may break a lot of the users

let me think through and let you know.

**Comment by vadimkhm** [comment] 2023-02-18 19:02
Hi, @rajanadar Thank you for the quick response. 

Yes I checked too, it is not a slight shift, but considering that even Net Core 3.1 reached the end of life in 2022 and .NET Standard 1.3 has reached the end of life too, is there a reason to keep them?

**Comment by rajanadar** [comment] 2023-02-19 04:31
Yeah makes. Sense, I have a branch in progress with the changes.

Let me finish the changes and by then I'll also make a call to deprecate the old versions.

I'll provide an update by next weekend.

**Comment by rajanadar** [comment] 2023-02-19 07:42
I made the 2300 odd changes. Build is successful.
Need to test the use cases over next week.

https://github.com/rajanadar/VaultSharp/pull/306

**Comment by hoerup** [comment] 2023-02-20 08:24
Before merging - consider the fact that it will break support for everything before net framework 4.7.2 as @rajanadar mentioned but that 4.6.2 is not EOL until 2027 and 4.7.0/4.7.1 doesn't yet have a EOL date defined

https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-framework

**Comment by rajanadar** [comment] 2023-02-20 08:33
Yes @hoerup.

There are a lot of test failures. Once I fix those, I'll probably release a beta nuget package for @vadimkhm.

It's too many breaking changes for the master pipeline of the packages.

**Comment by rajanadar** [comment] 2023-02-20 08:34
> Much appreciated! In case you need a helping hand, please let me know. I will be glad to assist.

Thanks @vadimkhm. It's fine. I have some momentum, making steady progress.

**Comment by vadimkhm** [comment] 2023-02-20 11:13
> Before merging - consider the fact that it will break support for everything before net framework 4.7.2 as @rajanadar mentioned but that 4.6.2 is not EOL until 2027 and 4.7.0/4.7.1 doesn't yet have a EOL date defined
> 
> https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-framework

You are right about these versions, but it is very easy to switch from them to 4.7.2, we did the same and moved to 4.8 from 4.6 without any issues. The converted project was not a small one.
But in the end, I can do a fork of @rajanadar's created branch and use it.

**Comment by rajanadar** [comment] 2023-03-04 08:11
@vadimkhm  You can see the progress on this branch btw.. Resolving one issue after the other..

https://github.com/rajanadar/VaultSharp/commits/sys-text-json-only

**Comment by rajanadar** [comment] 2023-03-04 18:55
@hoerup  What are your thoughts, if we remove support for the EOL versions only? Not for others.

So we would still support 4.6.2, 4.7, 4.7.1, 4.7.2, 4.8, 4.8.1, .NET Standard 2.0, .NET Standard 2.1, .NET 6.0
And support would be removed for the following EOL versions: 4.6, 4.6.1, .NET Standard 1.3, .NET 5.0

**Comment by rajanadar** [comment] 2023-03-25 20:06
@vadimkhm  I have published the official version of VaultSharp with this change. No more Newtonsoft Json dependency.
Feel free to take that update and let me know if any issues.

https://www.nuget.org/packages/VaultSharp/1.13.0

**Closed by rajanadar** 2023-03-25 20:06 UTC

**Comment by vadimkhm** [comment] 2023-03-26 07:16
@rajanadar cool, thank you very much!

**Comment by rajanadar** [comment] 2023-03-26 07:21
Thanks @vadimkhm for pointing me to this change. I think it's a good change for VaultSharp.

And hopefully, any future issues with json due to this change can be fix-forwards instead of rollbacks. Lets see.
