### ISSUE TITLE
AWS IAM authentication does not work

### ISSUE THREAD

**Issue by jdebbink** [rajanadar/VaultSharp#61] opened 2018-11-27 22:04 UTC
I've tried many things to get AWS IAM role authentication to work and every time I get the error from vault:
```
{"errors":["didn't supply required authentication values"]}
```

Here is what I have that I think *should* work but get the above error:
```csharp
var requestHeader = Convert.ToBase64String(Encoding.UTF8.GetBytes("{\"X-Vault-AWS-IAM-Server-ID\":[\"vault.example.com\"]}"));
var authMethod = new IAMAWSAuthMethodInfo(roleName: "my-role", requestHeaders: requestHeader);
```

I also didn't see an included example of this.

Here is a snippet in python/ruby where people report works for AWS IAM auth - https://gist.github.com/joelthompson/378cbe449d541debf771f5a6a171c5ed#file-vault_aws_auth_py3-py

Using the vault CLI I am able to auth:
```bash
vault auth -method=aws -token-only header_value=vault.example.com role=my-role
```

**Comment by rajanadar** [comment] 2018-11-28 00:16
@jdebbink 

This could be a VaultSharp issue or an issue with the requestHeader string logic.
In order to verify, can you please take a working requestHeaders string and put it directly on this line and check:

    var authMethod = new IAMAWSAuthMethodInfo(roleName: "my-role", requestHeaders: "good_one");

If the login succeeds, then VaultSharp is functioning as expected. There is a problem with the way IAM request headers are generated. Several people have hit issues with that.

e.g. https://groups.google.com/forum/#!topic/vault-tool/Mfi3O-lW60I

If the login doesn't succeed, let me know.

**Comment by jdebbink** [comment] 2018-11-28 21:19
I took the request headers from what was generated by the python script in the description and it did not work.

If you look at the error message that is coming back and compare it with the source code, you get that message when *none* of the required request headers are present.
https://github.com/hashicorp/vault/blob/d12547c7faa9c216d1411827bc16606535cb3e61/builtin/credential/aws/path_login.go#L366

I debugged this path and indeed 0 headers are added to the request. The `RequestHeaders` in `IAMAWSAuthMethodInfo` end up in the body of the POST (`HttpRequestMessage.Content`)

**Comment by rajanadar** [comment] 2018-11-30 04:05
good info @jdebbink .
I missed adding the header. I'll make that fix in the next release.

**Comment by jdebbink** [comment] 2018-11-30 15:08
Adding the header isn't enough, I tried.

You also need `iam_request_url` and `iam_request_body`.

I am also pretty sure the `iam_request_headers` in that are in the body of the POST need to be signed. 

Take a look at the vault example here and base64 decode the `iam_request_headers`: https://www.vaultproject.io/docs/auth/aws.html#via-the-cli

I am trying to get this to work, if I do I will share what I did.

**Comment by nsmeef** [comment] 2018-12-05 10:38
Need this in order to leverage this package for our systems. Do you need help implementing/fixing @rajanadar? (I haven't yet used so don't know where the implementation is up to).

**Comment by copperorange** [comment] 2018-12-17 15:11
Is anyone already looking at this? is help required?

**Comment by polsani** [comment] 2019-03-13 18:33
Is anyone already looking at this? Is help required? [2]

**Comment by rajanadar** [comment] 2019-03-13 19:35
I'll release a fix this weekend, for this.

**Comment by rajanadar** [comment] 2019-03-18 06:02
Testing this. Also finalizing to see if I should bother with a couple of other issues in this release. Please give it a couple more days.

**Comment by rajanadar** [comment] 2019-03-18 07:15
@jdebbink @nsmeef @copperorange  @polsani 

From the Vault API documentation https://www.vaultproject.io/api/auth/aws/index.html#login , it seems a client calling the Vault API, should provide the values in the Request Body. This is the Vault-API call's Request-Body. The Vault-Server may then be doing what is needed to package it as appropriate for an AWS IAM call.

I have added the 2 new mandatory values needed for IAM auth, as pointed out by @jdebbink 
I have released a beta version of the library, with just this fix.

https://www.nuget.org/packages/VaultSharp/0.11.1-beta1

Please verify and let me know.

**Comment by kenXengineering** [comment] 2019-03-18 19:48
I'm not sure what I'm doing that is wrong, but I am getting the following error.  I'm using  IAMAWSAuthMethodInfo passing only a nonce and role name.

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> VaultSharp.Core.VaultApiException: {"e
rrors":["error converting input QWN0aW9uPUdldENhbGxlcklkZW50aXR5JlZlcnNpb249MjAxMS0wNi0xNQ== for field \"iam_request_hea
ders\": invalid character 'A' looking for beginning of value"]}

   at VaultSharp.Core.Polymath.<MakeRequestAsync>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VaultSharp.Core.Polymath.<MakeVaultApiRequest>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VaultSharp.V1.AuthMethods.AWS.AWSAuthMethodLoginProvider.<GetVaultTokenAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VaultSharp.Core.Polymath.<MakeVaultApiRequest>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VaultSharp.V1.SecretsEngines.KeyValue.V2.KeyValueSecretsEngineV2Provider.<ReadSecretAsync>d__2.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at VaultIAMAuth.Program.Main(String[] args)
```

**Comment by rajanadar** [comment] 2019-03-19 05:17
@kenXengineering I have a default value for the iam request headers which is what Vault has on their documentation site. But their documentation suggests that this value can be a base 64 encoded string, or a jsonized key value string or a dictionary as well. I think it might be worth it to try a jsonized key value string and explicitly pass that to the Info object along with role a d nonce.

**Comment by polsani** [comment] 2019-03-19 19:30
Hi @rajanadar 
I was trying to use IAM authentication again using the code below. When using RoleId and SecretId it works fine, but when using IAM I'm gotting the message 

> AggregateException: One or more errors occurred. ({"errors":["error validating X-Vault-AWS-IAM-Server-ID header: missing Authorization header"]}

```
using System;
using System.Text;
using VaultSharp;
using VaultSharp.V1.AuthMethods.AWS;
using VaultSharp.V1.SecretsEngines.Transit;

namespace dotnet_vault_encrypt.Services
{
    public class VaultService : IVaultService
    {
        private const string VAULT_URL = "<my-vault-url";
        private const string KEY_NAME = "my-key-name";
        
        private readonly IVaultClient _vaultClient;
        private readonly string _context = Convert.ToBase64String(Encoding.UTF8.GetBytes("context"));

        public VaultService()
        {
            var requestHeader = Convert.ToBase64String(
                Encoding.UTF8.GetBytes("{\"X-Vault-AWS-IAM-Server-ID\":[\"my-vault-iam-server-id\"]}"));
            
            var authMethod = new IAMAWSAuthMethodInfo(
                httpRequestMethod: "POST", 
                requestHeaders: requestHeader,
                roleName: "my-role-name");
            
            var vaultClientSettings = new VaultClientSettings(VAULT_URL, authMethod);
            
            _vaultClient = new VaultClient(vaultClientSettings);
        }
        
        public string RequestEncrypt(string input)
        {
            var encryptOptions = new EncryptRequestOptions
            {
                Base64EncodedContext = _context,
                Base64EncodedPlainText = GetBase64EncodedString(input)
            };
            
            var encryptResponse = _vaultClient.V1.Secrets.Transit.EncryptAsync(KEY_NAME, encryptOptions).Result;
            return encryptResponse.Data.CipherText;
        }
        
        public string RequestDecrypt(string input)
        {
            var decryptOptions = new DecryptRequestOptions
            {
                CipherText = input,
                Base64EncodedContext = _context
            };

            var decryptionResponse = _vaultClient.V1.Secrets.Transit.DecryptAsync(KEY_NAME, decryptOptions).Result;

            return GetStringFromBase64Encoded(decryptionResponse.Data.Base64EncodedPlainText);
        }

        public DatabaseVaultModel GetDatabaseCredetials()
        {
            var credentials = _vaultClient.V1.Secrets.Database.GetCredentialsAsync("my-database-role").Result;
            
            return new DatabaseVaultModel
            {
                User = credentials.Data.Username,
                Password = credentials.Data.Password
            };
        }
        
        private string GetStringFromBase64Encoded(string encodedString)
        {
            var data = Convert.FromBase64String(encodedString);
            return Encoding.UTF8.GetString(data);
        }

        private string GetBase64EncodedString(string input)
        {
            return Convert.ToBase64String(Encoding.UTF8.GetBytes(input));
        }
    }

    public interface IVaultService
    {
        string RequestEncrypt(string input);
        string RequestDecrypt(string input);
        DatabaseVaultModel GetDatabaseCredetials();
    }

    public class DatabaseVaultModel
    {
        public string User { get; set; }
        public string Password { get; set; }
    }
}
```

The task-role is setted inside ecs container and I don't know about this Authorization header.
Do you have any idea what is going on?

Thank you in advance and for the library. It's awsome.

**Comment by oxlade39** [comment] 2019-03-20 18:53
I tried with the latest version (0.11.1-beta1) and this still doesn't work. 

When I compare it to a working python implementation in using it's missing the following headers:

- Authorization
- X-Amz-SecurityToken
- X-Amz-Date

The response I'm getting indicates that at the very least an Authorisation header is required. 

"error validating X-Vault-AWS-IAM-Server-ID header: missing Authorization header"

**Comment by oxlade39** [comment] 2019-03-20 21:32
I feel like I'm getting close to getting this working.
The following code gives me a 302 (redirect) response from STS when vault passes the request on. I get the feeling either my headers aren't correct or my sts url is wrong somehow, or maybe it needs the X-Amz-Security-Token header
```c#
            var awsRegion = Environment.GetEnvironmentVariable("AWS_REGION");
            var stsClient = new AmazonSecurityTokenServiceClient(RegionEndpoint.GetBySystemName(awsRegion));
            AWS4Signer signer = new AWS4Signer();
            var defaultRequest = new DefaultRequest(new GetCallerIdentityRequest(), "sts");
            defaultRequest.Endpoint = new Uri("https://sts.amazonaws.com/");
            defaultRequest.Headers.Add("X-Vault-AWS-IAM-Server-ID", host);
            AWSCredentials credentials = FallbackCredentialsFactory.GetCredentials();
            AWS4SigningResult result = signer.SignRequest(defaultRequest,
                stsClient.Config,
                new RequestMetrics(),
                credentials.GetCredentials().AccessKey,
                credentials.GetCredentials().SecretKey);
            var requestHeader = Convert.ToBase64String(Encoding.UTF8.GetBytes($"{{\"X-Vault-AWS-IAM-Server-ID\":[\"{host}\"], \"Authorization\": [\"{result.ForAuthorizationHeader}\"]}}"));

            var authMethod = new IAMAWSAuthMethodInfo(
                mountPoint: $"[!!!REDACTED!!!]",
                httpRequestMethod: "POST",
                requestHeaders: requestHeader,
                roleName: vaultRole);
//            IAuthMethodInfo info = new 
            var settings = new VaultClientSettings(_vaultUrl, authMethod);
```

**Comment by oxlade39** [comment] 2019-03-22 10:15
I've come up with the following working code to workaround the issue:
```c#
var authMethod = new AuthMethodInfoFactory(
                _vaultUrl, 
                "covar",                 
                $"aws/{REDACTED}/lambda",
                RegionEndpoint.GetBySystemName(awsRegion),
                FallbackCredentialsFactory.GetCredentials()).Create();
            var settings = new VaultClientSettings(_vaultUrl, authMethod);
```

```c#
    public class AuthMethodInfoFactory
    {
        private const string XVaultAwsIamServerIdHeader = "X-Vault-AWS-IAM-Server-ID";
        private readonly AWS4Signer _signer = new AWS4Signer();
        private readonly GetCallerIdentityRequestMarshaller _marshaller = new GetCallerIdentityRequestMarshaller();
        
        private readonly string _vaultUrl;
        private readonly string _authMount;
        private readonly string _vaultRole;
        private readonly RegionEndpoint _regionEndpoint;
        private readonly AWSCredentials _awsCredentials;

        public AuthMethodInfoFactory(string vaultUrl, string authMount, string vaultRole, RegionEndpoint regionEndpoint, AWSCredentials awsCredentials)
        {
            _vaultUrl = vaultUrl;
            _regionEndpoint = regionEndpoint;
            _authMount = authMount;
            _awsCredentials = awsCredentials;
            _vaultRole = vaultRole;
        }

        public IAuthMethodInfo Create()
        {
            var host = new Uri(_vaultUrl).Host;            
            ImmutableCredentials credentials = _awsCredentials.GetCredentials();
            var stsClient = new AmazonSecurityTokenServiceClient(_awsCredentials, _regionEndpoint);
            var endpointServiceName = stsClient.Config.RegionEndpointServiceName;
            var defaultRequest = CreateRequest(endpointServiceName);
            AddStandardHeaders(defaultRequest, host, stsClient);
            var signingResult = SignRequest(defaultRequest, stsClient, credentials);
            AddAuthHeaders(credentials, defaultRequest, signingResult);

            return CreateAuthMethodInfo(defaultRequest, _vaultRole);
        }

        private DefaultRequest CreateRequest(string endpointServiceName)
        {
            DefaultRequest defaultRequest = (DefaultRequest) _marshaller.Marshall(new GetCallerIdentityRequest());
            defaultRequest.Endpoint = new Uri($"https://{_regionEndpoint.GetEndpointForService(endpointServiceName).Hostname}", UriKind.Absolute);
            defaultRequest.ResourcePath = "/";
            return defaultRequest;
        }

        private static void AddStandardHeaders(DefaultRequest defaultRequest, string host, AmazonSecurityTokenServiceClient stsClient)
        {
            defaultRequest.Headers.Add(XVaultAwsIamServerIdHeader, host);
            defaultRequest.Headers.Add(HeaderKeys.ContentTypeHeader, AWSSDKUtils.UrlEncodedContent);
            defaultRequest.Headers.Add(HeaderKeys.UserAgentHeader, stsClient.Config.UserAgent);
        }

        private IAuthMethodInfo CreateAuthMethodInfo(DefaultRequest defaultRequest, string vaultRole)
        {
            string headersJson = JsonConvert.SerializeObject(defaultRequest.Headers);
            var requestHeader = Convert.ToBase64String(Encoding.UTF8.GetBytes(headersJson));
            return new IAMAWSAuthMethodInfo(
                _authMount,
                httpRequestMethod: "POST",
                requestHeaders: requestHeader,
                roleName: vaultRole);
        }

        private static void AddAuthHeaders(ImmutableCredentials credentials, DefaultRequest defaultRequest, AWS4SigningResult signingResult)
        {
            if (credentials.UseToken)
            {
                defaultRequest.Headers.Add(HeaderKeys.XAmzSecurityTokenHeader, credentials.Token);
            }

            defaultRequest.Headers.Add(HeaderKeys.AuthorizationHeader, signingResult.ForAuthorizationHeader);
        }

        private AWS4SigningResult SignRequest(DefaultRequest defaultRequest, AmazonSecurityTokenServiceClient stsClient, ImmutableCredentials credentials)
        {
            var signingResult = _signer.SignRequest(defaultRequest,
                stsClient.Config,
                new RequestMetrics(),
                credentials.AccessKey,
                credentials.SecretKey);
            return signingResult;
        }
    }
```

**Comment by copperorange** [comment] 2019-04-11 18:52
@rajanadar I think I ran into the same issue as above. Have you managed to take another look at this. @oxlade39 I have not tried your suggestion but am checking in to see if you have any updates or advice.

**Comment by jdebbink** [comment] 2019-04-11 20:44
I tried @oxlade39 code verbatim and I got a 400: missing client token error. My app runs in a Windows Docker container in ECS.

**Comment by oxlade39** [comment] 2019-04-11 20:54
@jdebbink sounds like the aws default credentials resolution isn't working for you. Maybe the `UseToken` property isn't true? 
It works for me, inside Lambda. I think ECS IAM is a slightly different method but I can't remember off top of my head

**Comment by jdebbink** [comment] 2019-04-11 20:57
@oxlade39 if you are talking about this line:
```
if (credentials.UseToken)
{
   ...
```
in `AddAuthHeaders`, I added logging to ensure it was hitting that condition and adding the token and it was.

**Comment by oxlade39** [comment] 2019-04-11 21:00
@jdebbink yes I was. Then I don't know but suspect it's something different about being in ECS. I'm pretty sure this exact code works for me but I can confirm tomorrow when I have the code Infront on me

**Comment by oxlade39** [comment] 2019-04-12 15:51
@jdebbink, just check and this is (apart from the redacted bit) verbatim the code we're using in our prod lambda functions and it's working, so I think it's either your `_authMount` is wrong or something different about doing this inside ECS, or your vault server configuration.

**Comment by copperorange** [comment] 2019-04-12 21:43
@oxlade39 @jdebbink I suspect the as you say something like the _authMount might be wrong for me as I am in a Lambda Function also. 
Exception:
{
    "errors": [
        "missing client token"
    ]
}
I'll dig a little deeper

**Comment by rajanadar** [comment] 2019-04-13 04:45
Folks, I'll be focusing on this this weekend.

**Comment by rajanadar** [comment] 2019-04-15 09:56
Folks, please use the following snippet and let me know if it solved your problem.

```
// Step 1: Pull the following NuGet Packages

// 1. AWSSDK.Core
// 2. AWSSDK.SecurityToken

// Step 2: Boiler-plate code to generate the Signed AWS STS Headers.

var amazonSecurityTokenServiceConfig = new AmazonSecurityTokenServiceConfig();

// If you are running VaultSharp on a real EC2 instance, use the following line of code.
// var awsCredentials = new InstanceProfileAWSCredentials();

// If you are running VaultSharp on a non-EC2 instance like local dev boxes or non-AWS environment, use the following line of code.

AWSCredentials awsCredentials = new StoredProfileAWSCredentials(); // picks up the credentials from your profile.
// AWSCredentials awsCredentials = new BasicAWSCredentials(accessKey: "YOUR_ACCESS_KEY", secretKey: "YOUR_SECRET_KEY"); // explicit credentials

var iamRequest = GetCallerIdentityRequestMarshaller.Instance.Marshall(new GetCallerIdentityRequest());

iamRequest.Endpoint = new Uri(amazonSecurityTokenServiceConfig.DetermineServiceURL());
iamRequest.ResourcePath = "/";

iamRequest.Headers.Add("User-Agent", "https://github.com/rajanadar/vaultsharp/0.11.1-beta1");
iamRequest.Headers.Add("X-Amz-Security-Token", awsCredentials.GetCredentials().Token);
iamRequest.Headers.Add("Content-Type", "application/x-www-form-urlencoded; charset=utf-8");

new AWS4Signer().Sign(iamRequest, amazonSecurityTokenServiceConfig, new RequestMetrics(), awsCredentials.GetCredentials().AccessKey, awsCredentials.GetCredentials().SecretKey);

// This is the point, when you have the final set of required Headers.
var iamSTSRequestHeaders = iamRequest.Headers;

// Step 3: Convert the headers into a base64 value needed by Vault.

var base64EncodedIamRequestHeaders = Convert.ToBase64String(Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(iamSTSRequestHeaders)));

// Step 4: Setup the IAM AWS Auth Info and generate login token.
IAuthMethodInfo iamAwsAuthMethodInfo = new IAMAWSAuthMethodInfo(
    roleName: "PROVIDE_ROLE_NAME",
    nonce: Guid.NewGuid().ToString(),
    requestHeaders: base64EncodedIamRequestHeaders);

VaultClientSettings iamAwsAuthVaultClientSettings = GetVaultClientSettings(iamAwsAuthMethodInfo);
IVaultClient awsIamVaultClient = new VaultClient(iamAwsAuthVaultClientSettings);
            
var iamAwsTokenResult = awsIamVaultClient.V1.System.GetCallingTokenCapabilitiesAsync("v1/sys").Result;
var iamAwsLoginAuthInfo = iamAwsAuthMethodInfo.ReturnedLoginAuthInfo;

Assert.NotNull(iamAwsLoginAuthInfo.ClientToken);
```

**Comment by rajanadar** [comment] 2019-04-16 23:21
@jdebbink @nsmeef @copperorange @polsani @kenXengineering @oxlade39 

Please check the new version of VaultSharp and let me know if the issue is solved.
Here is the sample, that shows how to generate valid IAM STS Request Headers. The AWS SDK is the best bet.

https://github.com/rajanadar/VaultSharp/blob/master/README.md#aws-auth-method---iam

**Comment by jdebbink** [comment] 2019-04-17 13:37
@rajanadar This method is missing: `GetVaultClientSettings`.

**Comment by jdebbink** [comment] 2019-04-17 14:06
@rajanadar Here is the error I get:
```
"StatusCode":500,"HttpStatusCode":500,"ApiErrors":["error converting input POST for field \"iam_request_headers\": invalid character '<' looking for beginning of value"
```

**Comment by rajanadar** [comment] 2019-04-17 14:39
What version of vault and VaultSharp are you in?

**Comment by jdebbink** [comment] 2019-04-17 14:55
Vault server: 1.1.0
VaultSharp: 0.11.1000

**Comment by rajanadar** [comment] 2019-04-18 01:25
hmm. okay. i tested my code with Vault 0.11.x
I think the Vault folks changed the request-headers field  to support multiple things. Dictionary, Json, Base64 etc. Let me est with Vault 1.1.0 and get back with an update.

**Comment by copperorange** [comment] 2019-04-18 03:34
@rajanadar It worked like a dream for me using 11.1.1-beta1 with Lambda but fails with the same message as @jdebbink for 0.11.1

**Comment by rajanadar** [comment] 2019-04-18 04:49
@copperorange Can you please clarify the Vault and VaultSharp version again?

**Comment by rajanadar** [comment] 2019-04-18 05:09
@jdebbink @copperorange 

Can you please try your samples with this overload of IAMAWSAuthMethodInfo class, and using 100% named parameters? Don't use the other overload of IAMAWSAuthMethodInfo. Let me know.

e.g.

```
IAuthMethodInfo authMethod = new IAMAWSAuthMethodInfo(mountPoint: AuthMethodType.AWS.Type, requestHeaders: base64EncodedIamRequestHeaders, nonce: "some_nonce", roleName: "some_role");
```

**Comment by copperorange** [comment] 2019-04-18 14:22
@rajanadar Vault Version 0.10.1, Version="0.11.1000"
OK. That worked for me. Note the only difference was the Mount Point

` 
IAuthMethodInfo iamAwsAuthMethodInfo = new IAMAWSAuthMethodInfo(
mountPoint: AuthMethodType.AWS.Type, 
requestHeaders: base64EncodedIamRequestHeaders, 
nonce: Guid.NewGuid().ToString(), 
roleName: _roleName);`

before

`
IAuthMethodInfo iamAwsAuthMethodInfo = new IAMAWSAuthMethodInfo(
roleName: _roleName,
nonce: Guid.NewGuid().ToString(),
requestHeaders: base64EncodedIamRequestHeaders);
`

**Comment by rajanadar** [comment] 2019-04-18 15:06
Fantastic. I have a bug in the constructor without the mount point. That's why the one without the mount point fails. If you use the constructor with the mount point, it works.

I'll fix the bug in a day. Then you should be able to use either constructor.

**Comment by rajanadar** [comment] 2019-04-20 08:14
I fixed the bug and published a newer version. All constructor overloads should be good to go. Closing this issue folks. Thanks for all the engagement.

**Closed by rajanadar** 2019-04-20 08:14 UTC
Labels: bug
