### ISSUE TITLE
No way to control proxy settings in client

### ISSUE THREAD

**Issue by agc93** [rajanadar/VaultSharp#11] opened 2016-09-08 02:04 UTC
Hi, thanks for an awesome library! Unfortunately, I can't use it in my environment as we need to specifically disable the proxy to access our Vault server, but it looks like there is no way to control the proxy settings of the `HttpClient` used by the `HttpDataAccessManager`. And since VaultClient is `internal`, there is no easy way to craft our own `IDataAccessManager` either.

Is there any possibility we will see some way of controlling  the `IDataAccessManager` that our `VaultClient` uses?

**Comment by rajanadar** [comment] 2016-09-08 02:42
hi @agc93 

thanks for using the library. (or at least for trying)

Release of VaultSharp 0.6.1 (or 0.6.2) is in progress, and i will definitely think through this issue and get a change in. (either expose an Action<HttpClient> delegate , or the httpclienthandler for some post-init on the factory, or somewhat similar to address the proxy issue.)

until then, there are a couple of workarounds i can suggest: (they are icky)

Option 1:

control the proxy settings via web.config or app.config:

```
<configuration >
  <system.net>
    <defaultProxy>
      <proxy bypassonlocal="true" usesystemdefault="false" />
    </defaultProxy>
  </system.net>
</configuration>
```

i haven't verified if this will truly affect the HttpClient instantiated by the library as part of your host app. (and if it does, it may affect all http clients in your app, and it may not be feasible to use it if you want proxy to be disabled for only Vault. in that case please see Option 2)

Options 2:

i have this issue marked for the next release for VaultSharp, to solve it the right way.
meanwhile, to get unblocked, you could try reflection and set the proxy as follows:

```

// assuming  _authenticatedVaultClient is IVaultClient

var dataAccessManagerField = _authenticatedVaultClient.GetType()
    .GetField("_dataAccessManager", BindingFlags.Instance | BindingFlags.NonPublic);

if (dataAccessManagerField != null)
{
    var dataAccessManager = dataAccessManagerField.GetValue(_authenticatedVaultClient);

    if (dataAccessManager != null)
    {
        var httpClientField = dataAccessManager.GetType()
            .GetField("_httpClient", BindingFlags.Instance | BindingFlags.NonPublic);

        if (httpClientField != null)
        {
            var httpClient = httpClientField.GetValue(dataAccessManager);

            if (httpClient != null)
            {
                var httpClientHandlerField = httpClient.GetType().BaseType
                    .GetField("handler", BindingFlags.Instance | BindingFlags.NonPublic);

                if (httpClientHandlerField != null)
                {
                    var httpClientHandler = httpClientHandlerField.GetValue(httpClient) as HttpClientHandler;

                    if (httpClientHandler != null)
                    {
                        // set proxy & related properties.
                    }
                }
            }
        }
    }
}
```

hope the above 2 options help you get unblocked TEMPORARILY to make use of the library's other features.

let me know if any issues.

i have assigned this issue for the upcoming release of the library.

**Comment by agc93** [comment] 2016-09-08 02:57
Oh wow, thanks @rajanadar for a fast and detailed response! I didn't seem to get the results I was looking for from the web.config change, but since I'm using DI for my `IVaultClient`, it should be pretty easy to integrate that reflection code in and get me going at least. Thanks!

Looking forward to 0.6.1 :smile:

**Comment by rajanadar** [comment] 2016-09-08 03:46
good to hear. cool.

**Comment by rajanadar** [comment] 2016-09-24 21:01
@agc93 

thought about a few options.. like taking in IProxy as a parameter in the factory method, messagehandler etc.. but decided to provide a simple post-processing delegate on the HttpClient instantiated. the callers are free to set proxy, add custom handlers etc.

it is an optional construct, so shouldn't affect existing callers. also nothing changed around the object structure so your existing reflection code should still work, if you choose to upgrade to vaultsharp 0.6.1 and decide not to leverage this delegate.

finishing up some new auth-role apis. and expect to close out 0.6.1 in a week.

**Comment by agc93** [comment] 2016-09-25 01:24
That sounds like a good approach @rajanadar and should allow enough options to control the client's behaviour without API changes, which sounds good.

Looking forward to 0.6.1 👍

**Comment by rajanadar** [comment] 2016-10-03 02:38
@agc93 0.6.1 is live now.. :+1:   
https://www.nuget.org/packages/VaultSharp/

it supports all the apis of vault 0.6.1 (including all new backends like mongodb, mssql, rabbitmq, aws-ec2, approle login etc.)

am updating the documentation now..

**Comment by bromanko** [comment] 2017-06-21 23:10
This doesn't appear to provide the desired functionality. The HttpClient instance doesn't allow customizing the HttpHandler. The only things you can change in this Action is the BaseAddress. Am I missing something? 

Perhaps it would be better to allow specifying the HttpClientHandler?

**Comment by monodop** [comment] 2018-01-04 01:09
I can confirm. This does not seem to fix the problem. [HttpClient](https://msdn.microsoft.com/en-us/library/system.net.http.httpclient(v=vs.118).aspx) does not have any means of changing proxy settings. If I'm missing something, I'd like to see an example of how you actually can make changes to the proxy settings, otherwise I think we'll need a new way to configure it.

**Comment by rajanadar** [comment] 2018-01-04 01:41
thanks @bromanko and @monodop . 

i should expose the handler out, not the client. this will be fixed as part of 0.9.x due in a couple of weeks.
if it is super blocking, please use the reflection method for a week or so. it is bad, but a stop-gap solution only.

**Comment by monodop** [comment] 2018-01-04 16:57
Thanks @rajanadar . I used the workaround above, but you have a typo.

```
var httpClientHandlerField = httpClient.GetType().BaseType
    .GetField("handler", BindingFlags.Instance | BindingFlags.NonPublic);
```

should be 

```
var httpClientHandlerField = httpClient.GetType().BaseType
    .GetField("_handler", BindingFlags.Instance | BindingFlags.NonPublic);
```

Thanks for getting the fix in so quickly though! I will look forward to 0.9.x 👍

**Comment by rajanadar** [comment] 2018-01-04 17:48
.thanks @monodop . glad that the workaround works for you.

as for the typo, can you please check again?

the "handler" is the name of the private field of the HttpClient class (in its base class HttpMessageInvoker) i don't see a prefix of underscore for that. (unless we are looking at different versions of .NET and it changed across versions)

let me know.

**Comment by monodop** [comment] 2018-01-04 17:51
The latest version of HttpMessageInvoker for .net core can be found here: https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpMessageInvoker.cs

It must have been renamed between the version you are using and the version I am using. Maybe it's just changed since .net core 2 or something.

**Comment by rajanadar** [comment] 2018-01-04 18:00
yes. ok. there's a reason we are not supposed to depended on reflection of private fields :)
have modified the snippet above to accommodate both field names. (based on what people are using)

either ways, all this is stop-gap. the next version has a clean handle to set proxy.

**Comment by pnquest** [comment] 2018-04-02 18:31
@rajanadar Just curious what the status of this milestone is?

**Closed** 2018-07-31 02:25 UTC
Labels: enhancement

**Comment by rajanadar** [comment] 2018-08-17 03:08
@agc93 @monodop @bromanko @pnquest 

The latest version of VaultSharp (0.10.x) is out.
It supports customization of the underlying http handler. Now you can set the proxy settings cleanly.

Do check it out.
