### ISSUE TITLE
Wrong documentation

### ISSUE THREAD

**Issue by hungnguyen1009** [rajanadar/VaultSharp#267] opened 2022-07-05 18:47 UTC
The library and documentation are not lined up together. The library could not able to support .NET Framework 4.6.2. Since v1.6.5.1 and up, all the library doesn't support .NET Framework 4.6.2

**Comment by hoerup** [comment] 2022-07-05 19:03
Duplicate of  #243

**Closed by hoerup** 2022-07-05 19:03 UTC
