### ISSUE TITLE
VaultSharp - Kerberos Authentication and Namespaces

### ISSUE THREAD

**Issue by intechdebt** [rajanadar/VaultSharp#170] opened 2020-12-10 16:19 UTC
We are having difficulties using VaultSharp and Kerberos authentication on Vault Enterprise with a namespace. Are there any special instructions for using kerberos authentication when a namespace is involved?

**Comment by rajanadar** [comment] 2020-12-10 16:29
Hey, is it working without the name space? And is it working with the name space with vault cli?

Whats your VaultSharp version and vault api version?

Any code snippet, any stack trace etc.

**Comment by intechdebt** [comment] 2020-12-11 14:08
Hi Rajandar,

Thanks for picking this up.

It works in our dev environment without the namespace.  We have tested it with the Vault CLI with a namespace, but have to use the following convoluted method to get it to work:

vault login  -method=kerberos  -output-curl-string    username=myuser    service=HTTP/vault.live.test.co.uk     realm=MYDOMAIN.LOCAL    keytab_path=vault.keytab      krb5conf_path=/etc/krb5.conf     disable_fast_negotiation=true

This spits out the curl command with the token:
curl -X PUT -H "Authorization: Negotiate YIIFl….. <snip>" -d 'null' https://vault.live.test.co.uk/v1/auth/kerberos/login

In order to get the curl command to work we have to add the header with the -H and set to the namespace: 
curl -X PUT -H "X-Vault-Namespace: mynamespace/app" -H "Authorization: Negotiate YIIFl….. <snip>" -d 'null' https://vault.live.test.co.uk/v1/auth/kerberos/login

The above works and authenticates using kerberos.

We are using the latest version of VaultSharp (1.6.0.1), Vault Enterprise v1.5.0 and API v3.0.2

I've attached some test code we put together and also a stack trace:
[Code.zip](https://github.com/rajanadar/VaultSharp/files/5679468/Code.zip)

[stacktrace.txt](https://github.com/rajanadar/VaultSharp/files/5679549/stacktrace.txt)

Kind regards,

Steve

**Comment by rajanadar** [comment] 2020-12-21 05:37
Thanks @intechdebt  Steve. This is very helpful.

**Comment by rajanadar** [comment] 2020-12-21 12:52
hey @intechdebt 

Just being super clear on one thing.

**Kerberos doesn't work for you, with or without Namespaces, using VaultSharp. Right? Please confirm.**

I wasn't clear on 

> "It works in our dev environment without the namespace..."

Does that mean that VaultSharp Kerberos worked for you without the namespace, and only with the namespace, it is giving you issues?

**Comment by rajanadar** [comment] 2020-12-25 06:07
@intechdebt  Please let me know.

**Comment by intechdebt** [comment] 2021-01-06 17:12
> hey @intechdebt
> 
> Just being super clear on one thing.
> 
> **Kerberos doesn't work for you, with or without Namespaces, using VaultSharp. Right? Please confirm.**
> 
> I wasn't clear on
> 
> > "It works in our dev environment without the namespace..."
> 
> Does that mean that VaultSharp Kerberos worked for you without the namespace, and only with the namespace, it is giving you issues?

Hi @rajanadar,

Our dev environment is not running the enterprise version of Vault and therefore does not support namespaces.  Kerberos authentication works OK in this environment. 

When we move our code in to the customer's environment it doesn't work.  This is running the enterprise edition of Vault and in this environment we have to use a namespace.  It is currently not possible for us to test in this environment without using a namespace.

**Comment by rajanadar** [comment] 2021-01-06 17:57
Thanks @intechdebt, this is very helpful.

It means that Kerberos by itself works. That's great to hear. It is only when namespaces are involved that it gets messed up. And I have a suspicion. 

For namespaces to work, VaultSharp pretty much sets the X-Vault-Namespace http header while making the call to vault server. It looks like this is not working as expected when the kerberos 401 Auth challenge flow is in progress. Maybe it's eating into the headers.

There are a couple of things, you can try out quickly.

1. Test it with the latest version of VaultSharp. I have added the **preauthenticate** flag to kerberos Auth. If this doesn't solve your name space problem, it'll at least prevent multiple round trips to your server. See this for more details.

https://weblog.west-wind.com/posts/2010/feb/18/net-webrequestpreauthenticate-not-quite-what-it-sounds-like

2. Also, VaultSharp gives the ability for you to intercept every http request sent by it to vault server. You can provide a delegate and do whatever you want to the http request before the request is fired off. The delegate can be set via VaultClientSettings' **BeforeApiRequestAction** delegate.

Please use that delegate to set the http header for the name space.

Let me know if the above helps you. 

Meanwhile, I'll try to repro this somehow or find out if kerberos and custom headers have issues. I see that you had to do some sorcery even in curl.

**Comment by intechdebt** [comment] 2021-01-07 12:04
Thanks @rajanadar for your assistance with our issue.

We have tried both of your suggested options and are still getting the 401 error.

**Comment by rajanadar** [comment] 2021-01-07 18:34
Thanks @intechdebt . That means, namespace is not the problem here.
Also, the stack trace says it is an auth error. Namespaces won't give that error. And also, you verified that namespaces were indeed set correctly.

While inspecting, were you able to see the "Authorization" header in the requests going from your web server to vault server?
From the stack trace it looks like, the first time itself when VaultSharp tries to kerberos-authenticate with Vault to get the vault token, it fails with 401, thus not even able to get the 1 time vault token.

This means, it is less of a namespace issue, and more of "if kerberos indeed works in your customer's environment?"
Can you check if the windows account (IIS?) under which your web app is running is not anonymous and is a proper domain account that is configured with permissions in the vault server of your customer env?

This is the exact line in VaultSharp that is failing and throwing an AggregateException with an inner VaultApiException of 401. And as you can see from the code, that line will succeed only if VaultSharp is able to present a valid SPNEGO (kerberos) token in the http header it sends out to vault server. Without a valid header, Vault server will throw back a 401 error and we don't have a vault token to proceed to your real read-secret method.

https://github.com/rajanadar/VaultSharp/blob/master/src/VaultSharp/V1/AuthMethods/Kerberos/KerberosAuthMethodLoginProvider.cs#L25

So can you please inspect the headers again and see if the SPNEGO Authorization header is sent by VaultSharp in the webb app to your vault server?

**Comment by intechdebt** [comment] 2021-01-08 14:25
Hi @rajanadar,

Thanks again for your detailed response.

Hashicorp have confirmed there is a bug in the Vault binary and that they are working on it.  It doesn’t add the namespace header, but if we add it manually we can log in. 
(Note I  tested an  LDAP login using the vault binary and it added the namespace header ok)

As far as VaultSharp libraries, I can clearly see the namespace header correctly being added without any intervention.

The application is currently running in Visual Studio in debug mode and  is using the domain authenticated user logged in on the desktop. I have both relied on the default Network credentials and also explicitly set the credential in my calls to the VaultSharp library. Same failure both times. Toggling the new preauthenticaion flag doesn’t change it either.

I think Kerberos authentication is failing for some reason and it is defaulting to NTLM. As a token (invalid one) is coming back, VaultSharp isn’t detecting this error. The Vault request has a Negotiate header but it doesn't look like a valid Kerberos token. 

From my  debug the login  request sent to Vault is :

+		_requestMessage	{Method: POST, RequestUri: 'https://vault.live.test.co.uk/v1/auth/kerberos/login', Version: 1.1, Content: <null>, Headers:
{
  X-Vault-Namespace: my/ns
  Authorization: Negotiate TlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAKADk4AAAADw==
}}	System.Net.Http.HttpRequestMessage

If I decode this "Negotiate" string I see the first few characters as;
"NTLMSSP  "
And the string is always the same, unlike a valid ticket.

Running klist on my windows desktop (that is running the app) does not show me a Kerberos ticket for Vault (whereas in my  dev environment I see one after a successful run of the code)
  
The spn in live  looks ok to me:
> setspn -l  'vaultaccount'
        HTTP/vault.live.test.co.uk
  
As confirmed by my setting service=HTTP/vault.live.test.co.uk in my "vault login -method=kerberos -output-curl-string  "  then adding the namespace header works ok 
  
My test code uses var vaultClientSettings = new VaultClientSettings("https://vault.live.test.co.uk", authMethod)  , from my understanding of SPN, even with https, the  SPN value in AD should be set to HTTP/vault.live.test.co.uk and not HTTPS. 
  
  Key differences in live:
  
  Production vault server is behind a load balancer 
  Production vault server is Enterprise version. Dev is community
  Production vault server is listening on https port 443.Vault server in dev is running http only on port 8200, ( & prod vault SSL  certificate is valid and its root ca is installed on testing desktop.)
  
Note: I get a similar failure in dev if I deliberately make the connection string (new VaultClientSettings("http://1.x.x.x:8200") mismatch the SPN entry ( e.g. by connecting to ip address http://1.x.x.x instead of the FQDN), it too gets exactly the same dodgy Negotiate string returned.
  
To progress further I am currently trying to see how to debug the Kerberos login to see if I can see what is going wrong.

**Comment by purplemog** [comment] 2021-01-08 18:51
Ive been working with intechdebt  and subsequent kerberos debugging in our environment has spotted a kerberos failed request for the dns A record  of the vault server  rather than the value we added as SPN (CNAME) .
  We will add the A record  to the SPN to  test this,  but If there is a way of setting something in the code to allow the alias to work we would be interested.  I am still investigating.
I see a ref to this on section Kerberos authentication and DNS CNAMEs on page https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-server-2010/gg502606(v=office.14)?redirectedfrom=MSDN
Thanks for the assistance so far!

**Comment by rajanadar** [comment] 2021-01-09 06:59
Thanks @purplemog for debugging this further. What a nasty issue.

While there is almost zero things that can be done in VaultSharp to control any Kerberos/DNS/CNAME customization, I have a very very crude suggestion to try based on a theory.

If cnane is indeed the issue, then the problem is that you are using cname for vault url (which is the desirable one, but doesn't work) instead of the A record (which is not desirable but that may work with KERBEROS)

Based on the above, while you try out your cname changes etc. here is another thing to try in VaultSharp. 

VaultSharp works in 2 steps. Step 1 is always about using the Auth method (kerberos login in this case) to get a pure vault token. This is a 1 time process in the lifetime of Vault Client. (unless you reinitialize vault client or explicitly request re login) Once this vault token is acquired as a one time thing, Step 2 is all about using this same token for all the vault business operations. Reading secrets etc. Step 2 has nothing to do with Kerberos at all, since we start step 2 with a vault token and that is all that's needed for authentication with vault server moving forward.

As of now, VaultSharp uses the same vault url for both steps. Because there is no reason for them to be different. But if we theorize that, kerberos will work with A record url, but I prefer Cname urls, then we can compromise as follows.

1. Initialize vault client with Kerberos Auth using the **A record url** as the vault url. And perform a dummy vault operation. This will ensure that Kerberos worked and more importantly you will now have access to the Vault Token in the 'Auth Info.ReturnedAuthInfo object'
2. You can now reinitialize another vault client with your cname url but doing a TokenAuthInfo instead of Kerberos. You use the token from above. (if you want to avoid reinitialization of the client again, you can also intercept the BeforeApiRequestAction delegate but you have to pretty much reset the whole HttpClient to change the url)

Because Auth is a one time thing, the time window of working with a A record is minimized and majority of your vault interactions are based on the desirable Cname url. As I said, not the ideal solution, but something to try. 

Let me know, how your side of things go as well.

**Comment by rajanadar** [comment] 2021-01-13 02:24
Hey, let me know if any updates.

**Comment by purplemog** [comment] 2021-01-13 08:16
So, I've submitted a request to add the SPN to active Directory for the real DNS name of the vault server, but this could take up to 2 weeks so I cant update on the progress of this. In the meantime I added a load balancer and did some testing in our testbed and the tests were consitent with my working theory. i.e
1) If the DNS entry in your url is a CNAME record, you need to add the SPN for the real underlying A record.
2) You dont need an SPN entry for the calling url as well, if it is a CNAME.
3) if using https, the calling url must be on the trusted vault ( or load balancer) certificate, trusted by the calling client host.
4) if using https, it doesnt matter if the A record doesnt have a trusted ssl cert hostname , as long at the calling url does.
5) All would be simpler if the calling url was a real A record, in which case ad dthe SPN for it and make sure if using https its hostname is valid/trusted on the valut ( or fronting load balncer  ssl cert)
Will update again once we get the SPN and test.

**Comment by rajanadar** [comment] 2021-01-13 08:37
Thanks so much for the update @purplemog

Is there anything on VaultSharp side pending? If not, I'll close the issue.

If this is an issue every kerberos community member is going to experience when they use a load balanced https based vault server then it may be worth to add a Readme section as the outcome learning of this exercise for VaultSharp users.

**Comment by purplemog** [comment] 2021-01-13 08:46
I'll check with @intechdebt  but I dont see any issue with the vaultsharp code. Ideally it would be helpful if the code detected the kerberos authenticaion failure. We only get an error when we make the call to say read a secret. And the error says the action is unauthorised. 
Thanks for your support. Vaultsharp is a great bit of code!

**Comment by rajanadar** [comment] 2021-01-24 17:26
> I'll check with @intechdebt but I dont see any issue with the vaultsharp code. Ideally it would be helpful if the code detected the kerberos authenticaion failure. We only get an error when we make the call to say read a secret. And the error says the action is unauthorised.

That's a good suggestion @purplemog . One of the challenges is when to attempt the authentication. Currently in VaultSharp, it does a deferred authentication when you attempt to perform the first real operation. (and not when you initialize the Auth info) My rationale for it, was to ensure you get a vault token that is as much alive as possible. However I do the downsides of it. No fast fail. Too late when the error happens.

Fast failure is preferred when there are auth failures. So let me add a flag to VaultClient settings (PerformImmediateAuth) which will attempt to login immediately when you are initializing VaultClient. And it should fail fast.

**Comment by rajanadar** [comment] 2021-01-24 17:27
closing this issue.

**Closed by rajanadar** 2021-01-24 17:27 UTC

**Comment by purplemog** [comment] 2021-02-05 07:46
So finally got the change implemented for the SPN in our environment and vault authenticating with kerberos to windows Actrive Directory nicely. Many thanks.

**Comment by rajanadar** [comment] 2021-02-05 07:47
Woot. That's very nice to hear @purplemog
